name: test
on:
  # run tests on push to master, but not when other branches are pushed to
  push:
    branches:
      - main

  # run tests for all pull requests
  pull_request:

jobs:
  buildnpush:
    name: Build and Push Docker Package
    #needs: [test, cross_compile, lint]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.JFROG_RESTIC_USERNAME }}
      PASSWORD: ${{ secrets.JFROG_RESTIC_PASSWORD }}
      GH_USERNAME: ${{ github.actor }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build image
        run: docker build --build-arg BUILD_DATETIME=${{ steps.date.outputs.date }} -t netapp-restic:latest .

      - name: Docker login
        run: docker login -u $USERNAME -p $PASSWORD netappdownloads.jfrog.io/oss-docker-restic-production/restic

      - name: Tag and push latest image
        run: |
          docker tag netapp-restic:latest netappdownloads.jfrog.io/oss-docker-restic-production/restic:latest
          docker push netappdownloads.jfrog.io/oss-docker-restic-production/restic:latest

      - name: Tag and push versioned image
        run: |
          export VERSION=$(cat NETAPPVERSION).${{ steps.date.outputs.date }}
          echo "VERSION="$VERSION
          docker tag netapp-restic:latest netappdownloads.jfrog.io/oss-docker-restic-production/restic:$VERSION
          docker push netappdownloads.jfrog.io/oss-docker-restic-production/restic:$VERSION

      - name: Tag and push to GitHub Container Registry
        run: |
          export VERSION=$(cat NETAPPVERSION)"."${{ steps.date.outputs.date }}
          echo "VERSION="$VERSION
          docker login -u $GH_USERNAME -p $GH_TOKEN ghcr.io/netapp/restic
          docker tag netapp-restic:latest ghcr.io/netapp/restic:latest
          docker push ghcr.io/netapp/restic:latest
          docker tag netapp-restic:latest ghcr.io/netapp/restic:$VERSION
          docker push ghcr.io/netapp/restic:$VERSION


